# Generated by Django 4.2.3 on 2023-07-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='invitation_link',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
