[tool.poetry]
name = "Virtual_App"
version = "1.6.0"
description = "Virtual Meeting App"
authors = ["BrodaOJ <brodaoj@gmail.com>"]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
